"""Document Engine data types — DocumentTree, TreeNode, NodeSummary, Document.

PageIndex-inspired hierarchical document representation. Plain dataclasses;
no DB coupling, no Memory Engine knowledge. Persisted via the
``DocumentStore`` SPI in Phase 2.

A ``Document`` is the top-level container. It has metadata (id, source
URI, content hash) and optionally a parsed ``DocumentTree``. The tree
contains nodes with parent/child relationships derived from document
structure (heading levels for markdown; TOC for PDFs).

Each ``TreeNode`` carries:
  - identity (id, parent_id, depth)
  - title (the heading text)
  - text (the body of the node, including the heading line)
  - optional summary + summary_kind (raw text vs LLM-generated)
  - children (list of TreeNode references — convenience, may be empty
    if loaded flat from storage)

Summary kinds (PageIndex parity):
  - "raw"  → summary IS the node text (small node, no LLM call)
  - "llm"  → summary was generated by an LLM (large node)
  - "prefix" → internal-node prefix-summary (covers its descendants)
"""

from __future__ import annotations

import hashlib
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Literal

SummaryKind = Literal["raw", "llm", "prefix"]


# ─── NodeSummary ──────────────────────────────────────────────────────


@dataclass
class NodeSummary:
    """A node's summary text plus how it was produced.

    Kept as a separate type so the summarizer can return ``None`` for
    nodes that don't need summarization and we keep ``TreeNode.summary``
    typed precisely.
    """

    text: str
    kind: SummaryKind = "raw"
    token_count: int | None = None

    def __len__(self) -> int:
        return len(self.text)


# ─── TreeNode ─────────────────────────────────────────────────────────


@dataclass
class TreeNode:
    """A single node in a DocumentTree.

    ``id`` and ``parent_id`` are UUIDs (as strings) so trees can be
    serialized / round-tripped through JSON without losing references.
    ``depth`` is 1-indexed (root depth=1, like markdown ``# heading``).
    """

    id: str
    parent_id: str | None
    depth: int  # 1..6 for markdown (h1..h6)
    title: str
    text: str = ""
    summary: NodeSummary | None = None
    children: list[TreeNode] = field(default_factory=list)
    # Optional source-location hints (line numbers in the original doc).
    line_start: int | None = None
    line_end: int | None = None

    @classmethod
    def new(cls, *, parent_id: str | None, depth: int, title: str, **kwargs: object) -> TreeNode:
        """Construct a TreeNode with a fresh UUID id."""
        if depth < 1 or depth > 6:
            raise ValueError(f"depth must be in 1..6, got {depth}")
        return cls(
            id=str(uuid.uuid4()),
            parent_id=parent_id,
            depth=depth,
            title=title,
            **kwargs,  # type: ignore[arg-type]
        )

    def add_child(self, child: TreeNode) -> None:
        """Append a child node, updating its parent_id for consistency."""
        child.parent_id = self.id
        self.children.append(child)

    def traverse_pre(self) -> list[TreeNode]:
        """Pre-order traversal — self before children. Returns flat list."""
        out: list[TreeNode] = [self]
        for c in self.children:
            out.extend(c.traverse_pre())
        return out

    def is_leaf(self) -> bool:
        return not self.children


# ─── DocumentTree ─────────────────────────────────────────────────────


@dataclass
class DocumentTree:
    """The hierarchical structure of one document.

    A tree has one or more root nodes (markdown may have multiple top-
    level headings; PDF typically one). ``document_id`` ties the tree
    to its source Document in storage.
    """

    document_id: str
    roots: list[TreeNode] = field(default_factory=list)

    def all_nodes(self) -> list[TreeNode]:
        """All nodes pre-order across all roots."""
        out: list[TreeNode] = []
        for r in self.roots:
            out.extend(r.traverse_pre())
        return out

    def node_count(self) -> int:
        return len(self.all_nodes())

    def find(self, node_id: str) -> TreeNode | None:
        for n in self.all_nodes():
            if n.id == node_id:
                return n
        return None


# ─── Document ─────────────────────────────────────────────────────────


@dataclass
class Document:
    """Top-level container — metadata + (optionally) parsed tree.

    A Document can exist without a tree (raw source held but not
    parsed yet); a tree always belongs to a Document.

    ``content_hash`` is a SHA-256 of the raw bytes/text — used by
    storage to dedupe identical re-uploads and by builders to cache
    summarization results.
    """

    id: str
    source_uri: str = ""  # file path, URL, "inline://", etc.
    content_hash: str = ""
    mime_type: str = "text/markdown"
    title: str = ""
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    tree: DocumentTree | None = None

    @classmethod
    def new(
        cls,
        *,
        source_uri: str = "",
        content: str | bytes = "",
        mime_type: str = "text/markdown",
        title: str = "",
    ) -> Document:
        """Construct a Document with a fresh id + content_hash."""
        if isinstance(content, str):
            content_bytes = content.encode("utf-8")
        else:
            content_bytes = content
        return cls(
            id=str(uuid.uuid4()),
            source_uri=source_uri,
            content_hash=hashlib.sha256(content_bytes).hexdigest(),
            mime_type=mime_type,
            title=title,
        )
