-- M17 Phase 2: Document Engine storage — tree nodes.
--
-- Closure-table style: each node row has a parent_id FK into the same
-- table, plus a document_id FK to the owning document. This shape
-- supports queries like:
--   - get all nodes for a document  (WHERE document_id = ?)
--   - get all roots                  (WHERE document_id = ? AND parent_id IS NULL)
--   - get all nodes at a depth       (WHERE document_id = ? AND depth = ?)
--   - get children of a node         (WHERE parent_id = ?)
-- without parsing JSON or walking nested structures in application code.
--
-- summary_kind values:
--   'raw'    — summary IS the node text (small node, no LLM call)
--   'llm'    — summary was generated by an LLM (large leaf node)
--   'prefix' — internal-node prefix-summary (covers its subtree)

CREATE TABLE IF NOT EXISTS astrocyte_document_nodes (
    id               UUID PRIMARY KEY,
    document_id      UUID NOT NULL REFERENCES astrocyte_documents(id) ON DELETE CASCADE,
    parent_id        UUID REFERENCES astrocyte_document_nodes(id) ON DELETE CASCADE,
    depth            SMALLINT NOT NULL CHECK (depth BETWEEN 1 AND 6),
    title            TEXT NOT NULL DEFAULT '',
    text             TEXT NOT NULL DEFAULT '',
    summary_text     TEXT,                              -- nullable; set after summarizer runs
    summary_kind     TEXT CHECK (summary_kind IN ('raw', 'llm', 'prefix')),
    summary_tokens   INTEGER,
    line_start       INTEGER,                           -- source line number (1-indexed)
    line_end         INTEGER,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Hot path: load all nodes for one document, ordered by line_start so
-- reconstruction reads sequentially through the source.
CREATE INDEX IF NOT EXISTS astrocyte_document_nodes_doc_line_idx
    ON astrocyte_document_nodes (document_id, line_start);

-- Children-of-node lookup.
CREATE INDEX IF NOT EXISTS astrocyte_document_nodes_parent_idx
    ON astrocyte_document_nodes (parent_id)
    WHERE parent_id IS NOT NULL;

-- Roots lookup (parent_id IS NULL is the marker for "top-level").
CREATE INDEX IF NOT EXISTS astrocyte_document_nodes_roots_idx
    ON astrocyte_document_nodes (document_id)
    WHERE parent_id IS NULL;

-- Depth-filtered queries (e.g., "all h2 nodes").
CREATE INDEX IF NOT EXISTS astrocyte_document_nodes_doc_depth_idx
    ON astrocyte_document_nodes (document_id, depth);
