"""PR2 commit A: per-section summary embeddings for the Tier-2 semantic strategy.

Embeds the ``summary`` text of each PageIndex tree section using the
configured embedding provider (typically ``text-embedding-3-small`` at
1536 dims). The vector lands in ``astrocyte_pi_sections.summary_embedding``
and powers the semantic strategy's `<=>` queries in PR2 commit B.

Why summary (not body):
- Body slices are 100-2000 tokens — embedding them is costly and the
  signal is noisy (full-turn dialogue contains a lot of social filler
  that dilutes the topical signal).
- The summary was generated by md_to_tree at retain time specifically
  to capture the section's topical content. It's the cleanest input
  we have for similarity ranking.

Why not body chunks too:
- Chunking the body into multiple embedded rows would push us back
  toward atomized retrieval (the M1-M8 shape). Section-grain is
  deliberate (ADR-007). Keep it.

Cost: one embedding API call per section. ``text-embedding-3-small``
costs ~$0.02 per 1M tokens; a typical section summary is ~50 tokens, so
~$0.000001 per section. Trivial vs the entity-extraction LLM call.

The embed call is batched per document (one network round-trip for all
sections in a tree) so retain wall-time stays bounded.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from astrocyte.providers.openai import OpenAIProvider
    from astrocyte.types import PageIndexSection

logger = logging.getLogger("astrocyte.pipeline.section_embedding")


async def embed_sections(
    provider: "OpenAIProvider",
    sections: list["PageIndexSection"],
    *,
    model: str | None = None,
) -> list[tuple[int, list[float]]]:
    """Batch-embed every section's summary in a single API call.

    Returns ``(line_num, vector)`` tuples for the subset of sections
    that have a non-empty summary; sections without a summary are
    silently skipped (their ``summary_embedding`` stays NULL — the
    semantic strategy excludes NULL rows naturally).

    ``model`` overrides the provider's default embedding model when
    set; otherwise the provider's configured model wins.
    """
    targets: list[tuple[int, str]] = [
        (s.line_num, (s.summary or "").strip())
        for s in sections
        if (s.summary or "").strip()
    ]
    if not targets:
        return []

    line_nums = [ln for ln, _ in targets]
    texts = [text for _, text in targets]

    try:
        vectors = await provider.embed(texts, model=model)
    except Exception as exc:  # noqa: BLE001 — embedding failure shouldn't tank retain
        logger.warning(
            "section_embedding: embed failed for %d sections — %s: %s",
            len(targets), type(exc).__name__, exc,
        )
        return []

    if len(vectors) != len(targets):
        logger.warning(
            "section_embedding: embed returned %d vectors for %d inputs",
            len(vectors), len(targets),
        )
        return []

    return list(zip(line_nums, vectors))
