"""Computed trend for observations based on evidence timestamps (M21).

A :class:`Trend` value indicates how an observation's supporting
evidence is distributed over time:

- :attr:`Trend.STABLE` — evidence spread across the analysis window,
  continues to present.
- :attr:`Trend.STRENGTHENING` — denser evidence recently than
  historically.
- :attr:`Trend.WEAKENING` — evidence mostly old, sparse recently.
- :attr:`Trend.NEW` — all evidence within the recent window.
- :attr:`Trend.STALE` — no evidence in the recent window (observation
  may no longer apply).

Trend is computed *algorithmically* from evidence timestamps, not
generated by the LLM, so it's cheap (microseconds per observation) and
deterministic — same evidence list always produces the same trend.

Thresholds (``recent_days=30``, ``old_days=90``) mirror Hindsight's
defaults; they're hard-coded in M21 (no config knob) and can be
exposed as :class:`~astrocyte.config.AstrocyteConfig` fields in a
future release if users ask. Tuning is unlikely to matter because
trends are *comparative* — STALE vs NEW for ranking, not absolute
day-counts.

Ported from Hindsight ``hindsight_api/engine/reflect/observations.py``
under the project's MIT licence.

See :class:`astrocyte.pipeline.observation.ObservationConsolidator` for
how trend is surfaced on consolidation results, and
:mod:`astrocyte.pipeline.orchestrator` for how trend is attached to
observation hits at recall time.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from enum import Enum


class Trend(str, Enum):
    """Computed trend for an observation based on evidence timestamps."""

    STABLE = "stable"
    STRENGTHENING = "strengthening"
    WEAKENING = "weakening"
    NEW = "new"
    STALE = "stale"


def _normalize_ts(ts: datetime) -> datetime:
    """Force a timestamp into UTC. Naive datetimes are assumed UTC."""
    if ts.tzinfo is None:
        return ts.replace(tzinfo=timezone.utc)
    return ts


def compute_trend(
    evidence_timestamps: list[datetime],
    *,
    now: datetime | None = None,
    recent_days: int = 30,
    old_days: int = 90,
) -> Trend:
    """Compute the trend for an observation from its evidence timestamps.

    Args:
        evidence_timestamps: Timestamps of the memories that support
            this observation. Empty list returns :attr:`Trend.STALE`.
            Order doesn't matter.
        now: Reference time for the analysis window. Defaults to
            ``datetime.now(timezone.utc)``. Naive datetimes are
            assumed to be UTC.
        recent_days: Days back from ``now`` that count as "recent".
            Default 30.
        old_days: Days back from ``now`` beyond which evidence counts
            as "old". Default 90. (Evidence between ``recent_days``
            and ``old_days`` counts as "middle".)

    Returns:
        A :class:`Trend` enum value.

    Algorithm:
        1. If no evidence at all → ``STALE``.
        2. If no evidence in the recent window → ``STALE``.
        3. If all evidence is in the recent window → ``NEW``.
        4. Compare density (evidence per day) in the recent vs. older
           periods:
           - ratio > 1.5 → ``STRENGTHENING``
           - ratio < 0.5 → ``WEAKENING``
           - otherwise → ``STABLE``
    """
    if now is None:
        now = datetime.now(timezone.utc)
    now = _normalize_ts(now)

    if not evidence_timestamps:
        return Trend.STALE

    recent_cutoff = now - timedelta(days=recent_days)
    old_cutoff = now - timedelta(days=old_days)

    normalized = [_normalize_ts(ts) for ts in evidence_timestamps]
    recent = [ts for ts in normalized if ts > recent_cutoff]
    old = [ts for ts in normalized if ts < old_cutoff]
    middle = [ts for ts in normalized if old_cutoff <= ts <= recent_cutoff]

    # No recent evidence at all → stale.
    if not recent:
        return Trend.STALE

    # All evidence is recent → new.
    if not old and not middle:
        return Trend.NEW

    # Compare density (evidence per day) in the recent window vs the older period.
    recent_density = len(recent) / recent_days if recent_days > 0 else 0.0
    older_period_days = old_days - recent_days
    older_density = (len(old) + len(middle)) / older_period_days if older_period_days > 0 else 0.0

    # If older density is zero but we got past the "no old/middle" check,
    # we have strictly recent + some boundary evidence — treat as NEW.
    if older_density == 0:
        return Trend.NEW

    ratio = recent_density / older_density
    if ratio > 1.5:
        return Trend.STRENGTHENING
    if ratio < 0.5:
        return Trend.WEAKENING
    return Trend.STABLE
