"""Phase A POC — vectorless reasoning-based RAG on LoCoMo via PageIndex.

Why this exists: the in-tree vector pipeline at HEAD scores ~50% on
LoCoMo on the same ``benchmarks/config-fast-recall.yaml`` that the
v0.13.0 baseline scored 83.28% with. The 33pp regression is in code
between v0.13.0 and HEAD and our config-knob bisect couldn't isolate
it. This script bypasses the entire vector retrieval path and tests
whether PageIndex's vectorless tree-search retrieval can land at or
above the v0.13.0 baseline with no Astrocyte pipeline involvement.

Pipeline:

1. **Markdown synthesis** — each LoCoMo conversation becomes one
   markdown document. Sessions are ``##`` headers including their
   wall-clock timestamp; turns are speaker-prefixed lines tagged with
   the original ``dia_id`` so the synthesised answer can cite the
   source. The headers are what PageIndex's tree-builder pivots on.

2. **Tree build (one-time per conversation)** — ``pageindex.md_to_tree``
   produces a hierarchical "table of contents" with per-node summary
   text generated by an LLM call. Built once before scoring; cached
   on disk so reruns skip rebuild.

3. **Per-question agent loop** — for each question:

   a. The conversation's tree skeleton (titles + summaries, no body
      text) is shown to an LLM along with the question.
   b. The LLM picks 1-3 ``line_num`` anchors that point at the
      sections most likely to contain the answer.
   c. We slice the markdown around those anchors (stop at the next
      ``##`` header) and feed the actual section text to a second LLM
      call which synthesises the final answer.

   That's a 2-call agent for the simple path. No tool-loop runtime
   because the search depth is bounded (one descend, one read) — the
   tree is small enough (a single conversation) that one round of
   navigation is sufficient. Aligns with PageIndex's "Vectorless RAG"
   recipe; we skip the OpenAI Agents SDK to keep the script
   dependency-free.

4. **Scoring** — reuses ``LoCoMoLLMJudge`` (the canonical yes/no judge
   the in-tree bench uses with ``--canonical-judge``) so results are
   directly comparable against v0.13.0's 83.28% baseline and the
   current pipeline's 50%.

Usage:
  doppler run -- uv run python scripts/bench_pageindex_locomo.py \\
      --max-questions-per-conversation 20

Targets:
  - overall ≥ 75%   (vs vector pipeline at HEAD: 50%)
  - adversarial ≥ 90%  (vs vector pipeline: 24-71%)
  - if either is reached, port to Astrocyte as a recall_strategy.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# PageIndex package is sibling to the astrocyte repo on the user's machine.
# We don't take a hard dep — just sys.path-shim it so this script runs
# without touching pyproject.toml. If we promote this to an Astrocyte
# adapter (Phase B), we'll add it as a proper workspace dep.
_PAGEINDEX_ROOT = Path("/Users/calvin/AstrocyteAI/PageIndex")
if str(_PAGEINDEX_ROOT) not in sys.path:
    sys.path.insert(0, str(_PAGEINDEX_ROOT))

from pageindex import md_to_tree  # noqa: E402

from astrocyte.eval.judges.locomo_judge import LoCoMoLLMJudge  # noqa: E402
from astrocyte.pipeline.section_embedding import embed_sections  # noqa: E402
from astrocyte.pipeline.section_entity_extraction import (  # noqa: E402
    extract_entities_for_section,
)
from astrocyte.providers.openai import OpenAIProvider  # noqa: E402
from astrocyte.testing.in_memory import InMemoryPageIndexStore  # noqa: E402
from astrocyte.types import (  # noqa: E402
    Message,
    PageIndexDocument,
    PageIndexSection,
)

# Astrocyte's category ID → name (kept local so this script doesn't
# import the LoCoMo bench harness — the harness imports a lot of
# pipeline machinery we deliberately bypass here).
_CATEGORY_MAP = {
    1: "multi-hop",
    2: "temporal",
    3: "open-domain",
    4: "single-hop",
    5: "adversarial",
}


# ───────────────────────────────────────────────────────────────────────────
# Markdown synthesis
# ───────────────────────────────────────────────────────────────────────────

def conversation_to_markdown(conv: dict, sample_id: str) -> str:
    """Render a LoCoMo conversation as PageIndex-friendly markdown.

    Sessions become ``## Session N (timestamp)`` headers — exactly what
    ``extract_nodes_from_markdown`` in PageIndex picks up as tree nodes.
    Each turn carries its original ``dia_id`` so the agent can cite
    sources (``D1:3``) the way the LoCoMo dataset annotates ground-truth
    evidence.
    """
    speaker_a = conv.get("speaker_a", "?")
    speaker_b = conv.get("speaker_b", "?")
    lines = [
        f"# Conversation {sample_id}",
        "",
        f"Participants: {speaker_a} and {speaker_b}",
        "",
    ]
    session_keys = sorted(
        (k for k in conv if k.startswith("session_") and "date" not in k),
        key=lambda k: int(k.split("_")[1]),
    )
    for sk in session_keys:
        date = conv.get(f"{sk}_date_time", "")
        turns = conv.get(sk) or []
        # Headers carry the timestamp inline so PageIndex's tree
        # summary-generator sees the date when it summarises a node.
        lines.append(f"## {sk.replace('_', ' ').title()} ({date})")
        lines.append("")
        for turn in turns:
            speaker = turn.get("speaker", "?")
            text = (turn.get("text") or "").replace("\n", " ").strip()
            dia_id = turn.get("dia_id", "")
            prefix = f"[{dia_id}] " if dia_id else ""
            lines.append(f"{prefix}**{speaker}**: {text}")
        lines.append("")
    return "\n".join(lines)


# ───────────────────────────────────────────────────────────────────────────
# Tree caching
# ───────────────────────────────────────────────────────────────────────────

async def _build_raw_tree(md_path: Path, model: str) -> dict:
    """Run md_to_tree once. Extracted so both file and store backends
    share the same expensive (~5-15 LLM calls) build step."""
    return await md_to_tree(
        str(md_path),
        if_add_node_summary="yes",
        summary_token_threshold=200,
        model=model,
        if_add_node_text="no",
        if_add_node_id="yes",
    )


def _conv_tree_dict(
    sample_id: str,
    md_text: str,
    tree: dict | list,
    session_dates: list[tuple[int, str]],
    *,
    document_id: str | None = None,
) -> dict:
    """Bundle the picker's working dict from the canonical pieces. The
    picker reads ``tree``/``md_text``/``session_dates``/``reference_date``;
    callers shouldn't construct this by hand.

    PR2 commit E: ``document_id`` is the store-assigned UUID for this
    sample's ``PageIndexDocument`` — used by the section recall path to
    address rows in section_entities / section_links queries. ``None``
    for the file backend.
    """
    return {
        "sample_id": sample_id,
        "md_text": md_text,
        "tree": tree,
        # Ordered list of (line_num, date_str) for the picker's temporal
        # routing prompt. Picker sees session anchors + their wall-clock
        # dates so it can binary-search to the right window.
        "session_dates": session_dates,
        # Anchor for the synthesiser's <reference_date> block — used to
        # resolve relative phrases like "two months ago" or "last week".
        # We pick the latest session as "now" because LoCoMo questions
        # are framed as if the user is looking back over the chat.
        "reference_date": session_dates[-1][1] if session_dates else None,
        # PR2-E: document_id for section recall lookup. None on file backend.
        "document_id": document_id,
    }


async def build_or_load_tree(
    conv: dict,
    sample_id: str,
    workspace: Path,
    model: str,
    *,
    store=None,  # PageIndexStore | None — when set, persist via SPI
    bank_id: str = "bench-pageindex-locomo",
    provider=None,  # PR2 commit A: LLMProvider for entity + embedding pass
    entity_model: str | None = None,
    embedding_model: str | None = None,
) -> dict:
    """Build a PageIndex tree for one conversation (or reuse cache).

    The tree-build is by far the most expensive one-time step
    (~5-15 LLM calls per conversation for summary generation). Caching
    by ``sample_id`` lets reruns of the bench skip it entirely while
    we iterate on the agent loop.

    Backends:
      - ``store=None`` (default): file-based cache at
        ``workspace/<sample_id>.tree.json`` (Phase A POC behaviour).
      - ``store=<PageIndexStore>``: PR1 commit C path — persist the
        tree as ``PageIndexDocument`` + ``PageIndexSection`` rows via
        the SPI. The picker still operates on the same in-memory dict
        shape; the only thing that changes is where the cached bytes
        live. Markdown is always re-written under ``workspace`` so the
        slicer can read it without round-tripping through the store
        (the store's md_text is the source of truth — the file mirror
        is just a fast-read scratch copy).
    """
    md_path = workspace / f"{sample_id}.md"

    # Always re-write the markdown — cheap and ensures the cached tree
    # was built from the current renderer's output. File-backend tree
    # cache is keyed off the markdown content via mtime check below;
    # store-backend uses (bank_id, source_id) + md_text equality.
    md_text = conversation_to_markdown(conv["conversation"], sample_id)
    md_path.write_text(md_text)

    if store is not None:
        return await _build_or_load_via_store(
            store=store,
            bank_id=bank_id,
            sample_id=sample_id,
            md_path=md_path,
            md_text=md_text,
            model=model,
            provider=provider,
            entity_model=entity_model,
            embedding_model=embedding_model,
        )

    # ── File-backend path (unchanged from Phase A) ──
    tree_path = workspace / f"{sample_id}.tree.json"
    if tree_path.exists() and tree_path.stat().st_mtime >= md_path.stat().st_mtime:
        cached = json.loads(tree_path.read_text())
    else:
        print(f"  [pageindex] Building tree for {sample_id} (file backend)...")
        cached = await _build_raw_tree(md_path, model)
        tree_path.write_text(json.dumps(cached, indent=2))

    nodes = cached.get("structure", cached) if isinstance(cached, dict) else cached
    session_dates = _enrich_nodes_with_dates(nodes)
    return _conv_tree_dict(sample_id, md_text, cached, session_dates)


async def _build_or_load_via_store(
    *,
    store,
    bank_id: str,
    sample_id: str,
    md_path: Path,
    md_text: str,
    model: str,
    provider=None,
    entity_model: str | None = None,
    embedding_model: str | None = None,
) -> dict:
    """PR1 commit D: tree-build path that persists through the
    ``PageIndexStore`` SPI. Cache key is ``(bank_id, sample_id)`` plus
    ``md_text`` equality (the conversation_to_markdown renderer is
    deterministic, so identical md_text means the cached sections are
    still valid)."""
    cached_doc = await store.load_document(bank_id, sample_id)
    cache_hit = cached_doc is not None and cached_doc.md_text == md_text

    if cache_hit:
        # Reconstruct the picker's nested-dict tree from the flat
        # sections. The picker prompt has been consuming this exact
        # shape since Phase A; the store-backed read path is shape-
        # equivalent to file-based load.
        sections = await store.load_skeleton(cached_doc.id)
        compact = _sections_to_compact_tree(sections)
        session_dates: list[tuple[int, str]] = [
            (s.line_num, _format_session_date(s.session_date))
            for s in sections
            if s.session_date is not None
        ]
        # Filter out any None date strings (shouldn't happen, but be safe).
        session_dates = [(ln, d) for ln, d in session_dates if d]
        return _conv_tree_dict(
            sample_id, md_text, compact, session_dates,
            document_id=cached_doc.id,
        )

    # Cache miss — run the expensive build, then persist.
    print(f"  [pageindex] Building tree for {sample_id} (store backend)...")
    raw_tree = await _build_raw_tree(md_path, model)
    nodes = raw_tree.get("structure", raw_tree) if isinstance(raw_tree, dict) else raw_tree
    session_dates = _enrich_nodes_with_dates(nodes)
    reference_date_dt = (
        _parse_session_date(session_dates[-1][1]) if session_dates else None
    )

    doc_to_save = PageIndexDocument(
        id="",  # ignored on insert; store assigns UUID and returns it
        bank_id=bank_id,
        source_id=sample_id,
        md_text=md_text,
        reference_date=reference_date_dt,
        built_at=datetime.now(tz=timezone.utc),
    )
    document_id = await store.save_document(doc_to_save)
    sections = _flatten_tree_to_sections(raw_tree, document_id)
    await store.save_sections(document_id, sections)

    # PR2 commit A: populate the entity + embedding indexes that PR2
    # commit B's parallel strategies will query against. Both calls are
    # gated on ``provider`` being available — when the bench is run
    # without a real LLM (smoke / file-backend mode), we skip cleanly so
    # the picker still works.
    if provider is not None:
        await _populate_section_index(
            provider=provider,
            store=store,
            document_id=document_id,
            sections=sections,
            md_text=md_text,
            entity_model=entity_model,
            embedding_model=embedding_model,
        )

    return _conv_tree_dict(
        sample_id, md_text, raw_tree, session_dates,
        document_id=document_id,
    )


async def _populate_section_index(
    *,
    provider,
    store,
    document_id: str,
    sections: list,
    md_text: str,
    entity_model: str | None,
    embedding_model: str | None,
) -> None:
    """PR2 commit A + D.7: extract entities + embed summaries +
    extract section links for every section in a freshly-built tree.

    Three passes, gathered concurrently:
    - Embeddings: one batched API call for the whole document.
    - Entities: one LLM call per section (~30 calls per LoCoMo conv).
    - Links (D.7): one LLM call per non-root section, looking back at
      the previous N section summaries for causal/supersedes/elaborates
      edges. The very first section has no prior, so it's skipped.

    Failures in any pass log a warning and degrade gracefully — the
    picker keeps working without these indexes, and PR2 commit B's
    strategies just return empty lists for unindexed sections.
    """
    from astrocyte.pipeline.section_link_extraction import (  # noqa: PLC0415
        extract_links_for_section,
    )

    # Sort sections by line_num so "prior" makes sense in document order.
    ordered_sections = sorted(sections, key=lambda s: s.line_num)

    # Run all three passes concurrently. Embeddings batch internally;
    # per-section LLM calls go in parallel via asyncio.gather.
    embed_task = embed_sections(provider, sections, model=embedding_model)
    entity_tasks = [
        extract_entities_for_section(
            provider, document_id, s,
            _slice_section_around_line(md_text, s.line_num),
            model=entity_model,
        )
        for s in sections
    ]
    # Link tasks: skip the first section (no prior context to link to).
    link_tasks = []
    for idx, s in enumerate(ordered_sections):
        if idx == 0:
            continue
        prior = ordered_sections[:idx]
        link_tasks.append(
            extract_links_for_section(
                provider, document_id, s,
                _slice_section_around_line(md_text, s.line_num),
                prior,
                model=entity_model,  # share the entity model knob; same gpt-4o-mini
            )
        )

    n_entity = len(entity_tasks)
    n_link = len(link_tasks)
    all_results = await asyncio.gather(
        embed_task, *entity_tasks, *link_tasks,
        return_exceptions=True,
    )
    embed_result = all_results[0]
    entity_results = all_results[1 : 1 + n_entity]
    link_results = all_results[1 + n_entity : 1 + n_entity + n_link]

    # Embeddings.
    n_embeddings = 0
    if isinstance(embed_result, Exception):
        print(f"  [pageindex] embed pass failed for doc={document_id}: {type(embed_result).__name__}")
    elif embed_result:
        await store.save_section_embeddings(document_id, embed_result)
        n_embeddings = len(embed_result)

    # Entities — flatten across sections, swallow per-section failures.
    all_entities = []
    for r in entity_results:
        if isinstance(r, Exception):
            continue
        all_entities.extend(r)
    if all_entities:
        await store.save_section_entities(all_entities)

    # Links (D.7) — flatten across sections, swallow per-section failures.
    all_links = []
    for r in link_results:
        if isinstance(r, Exception):
            continue
        all_links.extend(r)
    if all_links:
        await store.save_section_links(all_links)

    # PR2 D.7.1: semantic-kNN graph (no LLM cost). Runs AFTER
    # embeddings are saved so the SQL can read them. ``min_similarity``
    # filters near-zero noise — LME's chat-history shape produces lots
    # of weak similarities (different topics) that would only dilute
    # graph_expand if included.
    n_knn = 0
    if n_embeddings >= 2 and hasattr(store, "populate_semantic_knn_links"):
        try:
            n_knn = await store.populate_semantic_knn_links(
                document_id, top_k=5, min_similarity=0.5,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"  [pageindex] semantic_knn failed for doc={document_id}: {type(exc).__name__}: {exc}")

    print(
        f"  [pageindex] indexed doc={document_id}: "
        f"{len(all_entities)} entities, "
        f"{n_embeddings} embeddings, "
        f"{len(all_links)} llm-links, "
        f"{n_knn} knn-links"
    )


# ── Date extraction (regex; free) ─────────────────────────────────────────
#
# Section headers carry a date that the picker / synth use for temporal
# routing. Two formats supported:
#
# - LoCoMo: "Session 1 (1:56 pm on 8 May, 2023)" → "8 May, 2023"
# - LME:    "Session 1 (2023/05/20 (Sat) 02:21)" → "20 May, 2023"
#           (PR2 commit A — without this, every LME tree has zero
#           session_dates and temporal mode is dead on LME).
#
# Both regexes return the same human-readable form ("D Month, YYYY") so
# downstream code (synth's ``<reference_date>`` block, picker's
# session_date_index) is shape-stable across benches.
_DATE_RE = re.compile(
    r"\(\s*(?:\d{1,2}:\d{2}\s*(?:am|pm)\s*on\s+)?"
    r"(\d{1,2}\s+[A-Za-z]+,?\s+\d{4})\s*\)",
    re.IGNORECASE,
)
# LME format: "(2023/05/20 (Sat) 02:21)" — ISO-style date inside parens.
# The weekday + time are noise; we only care about Y/M/D.
_LME_DATE_RE = re.compile(
    r"\(\s*(\d{4})/(\d{1,2})/(\d{1,2})"
    r"(?:\s*\([A-Za-z]{3}\))?(?:\s+\d{1,2}:\d{2})?\s*\)",
)
_MONTH_NAMES = [
    "", "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]


def _extract_date_from_title(title: str) -> str | None:
    """Pull a normalised "D Month, YYYY" date out of a section title.

    Tries LoCoMo's `(1:56 pm on 8 May, 2023)` form first, then LME's
    `(2023/05/20 (Sat) 02:21)` ISO-with-weekday form. Returns ``None``
    when neither matches (caller falls back to NULL session_date)."""
    if not isinstance(title, str):
        return None
    m = _DATE_RE.search(title)
    if m:
        return m.group(1).strip()
    m = _LME_DATE_RE.search(title)
    if m:
        year, month, day = int(m.group(1)), int(m.group(2)), int(m.group(3))
        if 1 <= month <= 12:
            return f"{day} {_MONTH_NAMES[month]}, {year}"
    return None


def _enrich_nodes_with_dates(nodes: list | dict) -> list[tuple[int, str]]:
    """Walk a tree, attach `date` field on each node where parseable.

    Returns the ordered list of ``(line_num, date)`` pairs encountered —
    later passed to the picker so it sees a sortable date index.
    """
    found: list[tuple[int, str]] = []

    def _walk(n):
        if isinstance(n, list):
            for x in n:
                _walk(x)
            return
        if isinstance(n, dict):
            d = _extract_date_from_title(n.get("title", ""))
            if d:
                n["date"] = d
                ln = n.get("line_num")
                if isinstance(ln, int):
                    found.append((ln, d))
            sub = n.get("nodes")
            if sub:
                _walk(sub)

    _walk(nodes)
    return found


# ── Tree ↔ PageIndexSection conversion (PR1 commit D) ─────────────────────
#
# The picker operates on a nested-dict tree (post-``_strip_node_text``); the
# section recall store holds the same data as flat ``PageIndexSection`` rows. Two
# helpers bridge the shapes so we can persist trees to Postgres without
# touching the agent loop:
#
# - ``_flatten_tree_to_sections``: nested-tree → list[PageIndexSection]
#   (run after md_to_tree + ``_enrich_nodes_with_dates``; what gets written
#   to ``save_sections``).
# - ``_sections_to_compact_tree``: list[PageIndexSection] → nested dict
#   (run on cache-hit when reading from the store; produces the same shape
#   the picker prompt has been consuming since Phase A).

_MONTH_NUMBER = {
    name.lower(): idx
    for idx, name in enumerate(
        [
            "January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December",
        ],
        start=1,
    )
}
_DATE_PARSE_RE = re.compile(r"(\d{1,2})\s+([A-Za-z]+),?\s+(\d{4})")


def _parse_session_date(raw: str | None) -> datetime | None:
    """Parse '8 May, 2023' → tz-aware UTC datetime. Returns None on failure
    so callers can fall back to ``session_date IS NULL`` semantics."""
    if not raw:
        return None
    m = _DATE_PARSE_RE.search(raw)
    if not m:
        return None
    day, month_name, year = m.groups()
    month = _MONTH_NUMBER.get(month_name.lower())
    if month is None:
        return None
    try:
        return datetime(int(year), month, int(day), tzinfo=timezone.utc)
    except ValueError:
        return None


def _format_session_date(dt: datetime | None) -> str | None:
    """Inverse of ``_parse_session_date``: '8 May, 2023' form. The picker
    prompt expects this human-readable shape."""
    if dt is None:
        return None
    return dt.strftime("%-d %B, %Y")


def _flatten_tree_to_sections(
    tree: dict | list, document_id: str,
) -> list[PageIndexSection]:
    """Walk a nested md_to_tree-shape (post-``_enrich_nodes_with_dates``)
    and return the flat ``PageIndexSection`` list to write to the store.

    Skips nodes without an integer ``line_num`` (the picker can't address
    them and the store's PK requires it).
    """
    nodes = tree.get("structure", tree) if isinstance(tree, dict) else tree
    out: list[PageIndexSection] = []

    def _walk(items, parent_node_id, depth):
        if not isinstance(items, list):
            return
        for n in items:
            if not isinstance(n, dict):
                continue
            line_num = n.get("line_num")
            if not isinstance(line_num, int):
                continue
            out.append(
                PageIndexSection(
                    document_id=document_id,
                    line_num=line_num,
                    node_id=n.get("node_id", "") or "",
                    title=n.get("title", "") or "",
                    summary=n.get("summary") or n.get("prefix_summary"),
                    speaker=None,  # PR2 commit C — speaker tag for LME assistant-recall
                    session_date=_parse_session_date(n.get("date")),
                    parent_node=parent_node_id,
                    depth=depth,
                )
            )
            sub = n.get("nodes")
            if sub:
                _walk(sub, n.get("node_id"), depth + 1)

    _walk(nodes, None, 0)
    return out


def _sections_to_compact_tree(
    sections: list[PageIndexSection],
) -> list[dict]:
    """Reconstruct the picker's nested-dict tree from a flat section list.

    Inverse of ``_flatten_tree_to_sections``. Groups by ``parent_node``
    (root nodes have ``parent_node=None``) and emits the same key shape
    the picker prompt has been consuming (title, node_id, line_num,
    summary, date, nested ``nodes``). The cache-hit path through the
    section recall store goes through this function.
    """
    by_parent: dict[str | None, list[PageIndexSection]] = {}
    for s in sections:
        by_parent.setdefault(s.parent_node, []).append(s)

    def _build(parent_node_id: str | None) -> list[dict]:
        children = sorted(
            by_parent.get(parent_node_id, []),
            key=lambda s: s.line_num,
        )
        out: list[dict] = []
        for s in children:
            node: dict = {
                "title": s.title,
                "node_id": s.node_id,
                "line_num": s.line_num,
            }
            if s.summary:
                node["summary"] = s.summary
            date_str = _format_session_date(s.session_date)
            if date_str:
                node["date"] = date_str
            sub = _build(s.node_id)
            if sub:
                node["nodes"] = sub
            out.append(node)
        return out

    return _build(None)


# ───────────────────────────────────────────────────────────────────────────
# Agent loop
# ───────────────────────────────────────────────────────────────────────────

def _strip_node_text(tree: list | dict) -> list | dict:
    """Strip ``text`` field from tree nodes, preserving structure +
    summaries. PageIndex sometimes carries body text on nodes; the
    skeleton we pass to the picker LLM should NOT include it (the
    whole point of the two-step retrieval is the LLM picks before
    seeing the bodies)."""
    if isinstance(tree, list):
        return [_strip_node_text(n) for n in tree]
    if isinstance(tree, dict):
        out = {k: v for k, v in tree.items() if k != "text"}
        if "nodes" in out:
            out["nodes"] = _strip_node_text(out["nodes"])
        return out
    return tree


def _slice_section_around_line(md_text: str, line_num: int) -> str:
    """Return the markdown section starting at ``line_num`` until the
    next ``##`` header (or EOF). 1-indexed line numbers (matches
    PageIndex's ``line_num`` field convention)."""
    lines = md_text.split("\n")
    if line_num < 1 or line_num > len(lines):
        return ""
    out_lines: list[str] = [lines[line_num - 1]]
    for line in lines[line_num:]:
        if line.startswith("## "):
            break
        out_lines.append(line)
    return "\n".join(out_lines).strip()


def _collect_valid_line_nums(tree: list | dict, out: list[int] | None = None) -> list[int]:
    """Extract every section-anchor ``line_num`` from a tree.

    The picker's job is to choose ``##`` section anchors — the
    smoke run on 2026-05-09 showed gpt-4o-mini routinely hallucinated
    line numbers that fell inside a section's body (or in the
    pre-Session-1 conversation header), and the slice helper then
    returned garbage that synthesised to "Not in the provided
    memories". Restricting picks to this allowlist eliminates that
    failure class entirely. Sorted ascending so the picker prompt
    can present them as a consistent menu.
    """
    if out is None:
        out = []
    if isinstance(tree, list):
        for n in tree:
            _collect_valid_line_nums(n, out)
        return out
    if isinstance(tree, dict):
        ln = tree.get("line_num")
        if isinstance(ln, int):
            out.append(ln)
        if tree.get("nodes"):
            _collect_valid_line_nums(tree["nodes"], out)
    return sorted(set(out))


# ── Question-mode detection ────────────────────────────────────────────
#
# LoCoMo categories drive different retrieval shapes:
#
# - temporal ("when did X?", "how long after Y?", "in May 2023") — needs
#   date-anchored picking + a reference_date the synthesiser can use to
#   resolve relative phrases.
# - open-domain / listing ("everything about X", "all the jobs Jon held",
#   "which X do they like") — needs *every* session mentioning the
#   subject, not the top-k. Synthesiser must enumerate + dedupe instead
#   of producing a one-sentence answer.
# - multi-hop (default for compound questions) — needs a bigger pick
#   budget so chained evidence can land in scope.
#
# Heuristic regex over the question text. Cheap; mis-routing back to
# default is harmless (default is the strict superset of multi-hop).
_LISTING_PATTERNS = [
    r"\beverything\b",
    r"\ball\s+(?:the\s+|of\s+)?",
    r"\bevery\s+",
    r"\blist\s+(?:the\s+|all\s+)?",
    r"\bwhat\s+are\s+(?:the|all)\b",
    r"\bnames?\s+of\s+",
    r"\bwhich\s+\w+s\b",  # plural noun → likely listing
]

# PR2 D.7.2: counting/sum question patterns. LME multi-session is
# 78% counting/sum questions ("how many doctors", "how much spent",
# "total hours"). The PR2-D.7 gate showed graph_expand correctly
# bridges sessions but the synth undercounts because the picker
# returns top-K (5-6) sections — insufficient for exhaustive
# enumeration when the answer needs 8-10 mentions.
#
# Routing these to ``listing`` mode (PICK_PROMPT_LISTING +
# SYNTHESIZE_PROMPT_LISTING) makes the picker fetch ALL relevant
# sections, which is the same fix that lifted LoCoMo open-domain
# from 33→67% in PR2-D.1-4 for "every / all / list" questions.
_COUNTING_PATTERNS = [
    r"\bhow\s+many\s+(?!days?\s+(?:passed|elapsed|ago)|weeks?\s+(?:passed|elapsed|ago)|months?\s+(?:passed|elapsed|ago)|years?\s+(?:passed|elapsed|ago))",
    r"\bhow\s+much\s+(?:total|money|did|do|have)",
    r"\b(?:total|sum)\s+(?:number|amount|money|cost|hours?|days?|weeks?|months?|years?)\b",
    r"\bcount\s+(?:of|the)\s+",
]


def _is_counting_question(question: str) -> bool:
    """PR2 D.7.2: detect counting/sum questions that need listing-shape
    retrieval. The ``how many days passed`` / ``how many weeks ago``
    patterns are EXCLUDED — those are handled by D.5.5's date-arithmetic
    short-circuit, not listing.
    """
    q = question.lower()
    return any(re.search(p, q) for p in _COUNTING_PATTERNS)

_TEMPORAL_PATTERNS = [
    r"\bwhen\s+(?:did|was|were|does|will|do)\b",
    r"\bwhat\s+(?:date|day|month|year|time)\b",
    r"\bhow\s+(?:long|many\s+(?:days|weeks|months|years))\b",
    r"\bafter\s+how\s+",
    r"\bbefore\s+(?:she|he|they|going|the)\b",
    r"\b(?:january|february|march|april|may|june|july|august|september|october|november|december)\b",
    r"\b(?:19|20)\d{2}\b",  # year mention
    r"\blast\s+(?:week|month|year|night|time)\b",
    r"\b(?:two|three|four|five|six|seven|eight|nine|ten|\d+)\s+(?:days?|weeks?|months?|years?)\s+(?:ago|later|before|after)\b",
]


# PR2 D.3: regex patterns for "this is an inference question" — used
# both for LoCoMo open-domain (most of which are inference-shaped, not
# listing-shaped) and LME single-session-preference. When detected,
# the synth uses ``SYNTHESIZE_PROMPT_INFERENCE`` which is permissive
# about reading-between-the-lines instead of abstaining.
_INFERENCE_PATTERNS = [
    r"\bwould\s+\w+\s+(enjoy|like|prefer|want|consider|choose|appreciate)",
    r"\bwhat\s+(might|may)\b",
    r"\bis\s+it\s+(likely|possible|probable)\b",
    r"\bdo\s+you\s+think\b",
    r"\bcould\s+\w+\s+(have|be|do)",
    r"\bwhat['']s\s+an?\s+\w+\s+\w+\s+would\s+(like|enjoy)",  # "what's an activity X would enjoy"
    r"\bgiven\s+(?:that|what)\b",  # "given what we know about X"
]


# PR2 D.4: answer-type hint table. Maps question-shape patterns to
# the type the answer MUST match. The inference synth uses this to
# verify its final answer before emitting (avoids the "Boston" =
# city-not-country failure).
_ANSWER_TYPE_PATTERNS = [
    (r"\bwhat\s+country\b|\bwhich\s+country\b|\bin\s+what\s+country\b", "country"),
    (r"\bwhat\s+city\b|\bwhich\s+city\b|\bin\s+what\s+city\b", "city"),
    (r"\bwhat\s+year\b|\bwhich\s+year\b|\bin\s+what\s+year\b", "year"),
    (r"\bwhat\s+month\b|\bwhich\s+month\b", "month"),
    (r"\bwhat\s+(?:date|day)\b", "date"),
    (r"\bwho\b.*\b(?:did|was|met|saw|met with)\b", "person"),
    (r"\bhow\s+old\b|\bwhat\s+age\b", "age (number)"),
    (r"\bhow\s+(many|much)\b", "number / quantity"),
]


def _detect_answer_type_hint(question: str) -> str:
    """PR2 D.4: emit a one-word hint about the expected answer type.
    The inference synth uses this to verify its final answer matches
    the asked-for type. Returns an empty string when no hint applies."""
    q = question.lower()
    for pattern, hint in _ANSWER_TYPE_PATTERNS:
        if re.search(pattern, q):
            return hint
    return ""


def _is_inference_question(question: str) -> bool:
    """PR2 D.3: classify whether a question is inference-shape."""
    q = question.lower()
    return any(re.search(p, q) for p in _INFERENCE_PATTERNS)


# PR2 D.1: explicit category → mode mapping for benches that already
# carry a question_type label. LoCoMo uses these category integers
# (mapped via ``_CATEGORY_MAP``); LME uses string labels directly.
# Both should bypass the regex heuristic — the dataset *knows* which
# kind of question this is.
_CATEGORY_TO_MODE = {
    # LoCoMo (string labels post-_CATEGORY_MAP)
    "multi-hop": "multi-hop",
    "temporal": "temporal",
    "open-domain": "default",  # most open-domain are inference; D.3 adds inference mode
    "single-hop": "default",
    "adversarial": "default",
    # LME (string labels from question_type)
    "single-session-user": "default",
    "single-session-assistant": "single-session-assistant",
    "single-session-preference": "default",  # inference-shape; D.3 will route to 'inference'
    "multi-session": "multi-session",
    "temporal-reasoning": "temporal-reasoning",
    "knowledge-update": "knowledge-update",
}


def _detect_question_mode(
    question: str,
    *,
    category: str | None = None,
) -> str:
    """Return a mode label for picker / synth dispatch.

    PR2 D.1: when ``category`` is provided (every bench question has
    one), use the explicit category → mode map. The regex heuristic is
    only a fallback for callers without a category — neither LoCoMo
    nor LME hits that path. The previous implementation ignored
    category and returned wrong modes for every LME multi-session /
    temporal-reasoning question, which is why those categories scored
    0% in the PR2 LME gate.

    Returned modes are passed verbatim to ``section_recall``'s
    ``select_strategies_for_mode``; both ends agree on the same string
    constants.
    """
    if category:
        mapped = _CATEGORY_TO_MODE.get(category)
        if mapped:
            return mapped

    # Fallback: regex heuristic on question text. Used for ad-hoc
    # callers without a category label.
    q = question.lower()
    for p in _LISTING_PATTERNS:
        if re.search(p, q):
            return "listing"
    for p in _TEMPORAL_PATTERNS:
        if re.search(p, q):
            return "temporal"
    return "default"


# ── Picker prompts ─────────────────────────────────────────────────────
#
# Three modes, each with a different selection bias. The default prompt
# stays close to the v4 shape but with a bumped budget so multi-hop
# chains have room to land in scope.

PICK_PROMPT_DEFAULT = """You are routing a user question to the right section(s) of a long conversation transcript.

Below is the conversation's "table of contents" — each node is a session header with its date and a one-paragraph summary. Sessions are ordered chronologically.

ALWAYS pick at least 4 line_num values — never return an empty list. Your job is selection, not abstention; the downstream synthesiser decides whether the picked sections actually answer the question. Picking too few makes false-negative abstentions inevitable; picking too many is cheap (synth filters).

Sizing the pick:
- Direct single-fact lookup ("what's X's job?", "where does Y live?") → 4-6 sections.
- **Multi-hop / compound** ("what do X and Y have in common?", "X's reason for Y's outcome?") → **7-12 sections**. CRUCIAL: if the question mentions multiple distinct people or topics, ensure your picks include sections that mention EACH ONE separately — don't only pick co-mention sessions, those may not exist. Better to pick one session per subject and let the synthesiser join.
- Adversarial-shaped questions: still pick 5-8 sections that touch any related topic; let the synthesiser refuse if support is genuinely absent.

Read summaries for keyword matches, topic continuity, and dates that match the question. Answers often sit in sessions with non-obvious summaries — when in doubt, include the session.

Pick line_nums ONLY from this allowlist (these are the real section anchors): {valid_lines}

Tree (titles + summaries):
{tree_json}

Question: {question}

Output ONLY a JSON object: {{"line_nums": [<int>, ...], "reason": "<one short sentence>"}}"""


PICK_PROMPT_TEMPORAL = """You are routing a TIME-SENSITIVE question to the right session(s).

The conversation is broken into dated sessions. Below is the session date index in chronological order — line_num → date:
{session_date_index}

Reference date (the conversation's last session, treat as "today"): {reference_date}

Pick AT LEAST 5 line_nums covering:
1. The session whose date matches the question's time anchor most closely (or covers the asked period). For relative phrases ("last week", "two months ago"), compute against the reference date.
2. The IMMEDIATE NEIGHBOURS of (1) — temporal questions often span session boundaries (the event is mentioned in one session and dated in another).
3. Earlier sessions whose summary mentions the same subject — answers may be set up earlier and confirmed later.
4. The session immediately following any "I'll do X next month" mention — that's where confirmation lands.

If the question is "when did X happen?" you MUST include the session where X is first mentioned (often not the one with the matching date — the date may only be in the speaker's recap a session or two later).

Pick line_nums ONLY from this allowlist: {valid_lines}

Tree (titles + summaries — `date` field on each node):
{tree_json}

Question: {question}

Output ONLY a JSON object: {{"line_nums": [<int>, ...], "reason": "<one short sentence>"}}"""


PICK_PROMPT_LISTING = """You are answering a LISTING / AGGREGATION question. The user wants every distinct fact about a subject — no single session contains the full list.

Pick **EVERY** session whose summary mentions the subject, related themes, activities, people, or time period. Err HEAVILY on the side of inclusion: false-positives are cheap (the synthesiser dedupes), but a missed session leaves a gap in the list.

Pick AT LEAST 8 line_nums; ideally every session that touches the topic. Cap at 12 to fit the synth context.

Pick line_nums ONLY from this allowlist: {valid_lines}

Tree (titles + summaries):
{tree_json}

Question: {question}

Output ONLY a JSON object: {{"line_nums": [<int>, ...], "reason": "<one short sentence>"}}"""


# ── Synthesiser prompts ────────────────────────────────────────────────

SYNTHESIZE_PROMPT_DEFAULT = """You are answering a question from a conversation transcript.

<reference_date>{reference_date}</reference_date>
(The conversation's most recent session — treat this as "today" when the question uses relative time phrases like "last week" or "two months ago".)

Use ONLY the conversation excerpts below. If the excerpts genuinely don't answer the question, respond exactly: "Not in the provided memories."

ONE strict rule: if the question names a PERSON who does NOT appear in any excerpt as a speaker or subject, respond exactly: "Not in the provided memories." Do NOT substitute a different person from the conversation — just abstain.

Composition and inference ARE allowed and expected:
- For multi-hop questions, COMBINE facts from different excerpts — e.g. "Jon lost his banker job (D5:3) and Gina lost her studio job (D7:1); both started their own businesses (D9:2, D11:4)".
- For inference questions ("would X enjoy", "is it likely", "what might"), draw a reasonable inference from the excerpts — these questions are answered by reading between the lines, not by direct quotation.
- For temporal questions, look at the session-date suffix (e.g. "## Session 5 (8 May, 2023)") AND explicit dates inside turns. Compute relative phrases against the reference date above.

Cite dia_id (e.g. D1:3) only when it appears in the excerpts.

Excerpts:
{excerpts}

Question: {question}

Be concise. Answer:"""


SYNTHESIZE_PROMPT_INFERENCE = """You are answering an INFERENCE question from a conversation transcript.

<reference_date>{reference_date}</reference_date>
<answer_type_hint>{answer_type_hint}</answer_type_hint>

The user wants you to *read between the lines* of related context, not quote a direct answer. The answer typically won't appear verbatim — your job is to combine signals from multiple excerpts into a single judgment.

Examples of inference shape:
- "Would Tim enjoy X?" → look at Tim's stated preferences in adjacent domains; if they overlap with X, answer YES with the supporting excerpt cited.
- "What might X's status be?" → list the indicators in excerpts and pick the most-supported conclusion.
- "Is it likely Y?" → look for evidence both ways; answer YES/NO with the dominant signal.
- "What's an indoor activity X would enjoy?" → infer from X's known hobbies / personality / family situation, even if no excerpt names that specific activity.

ABSTAIN ONLY when the excerpts contain ZERO signal about the question subject — not when the answer requires interpretation.

PR2 D.4: if ``answer_type_hint`` is set (e.g. 'country', 'city', 'year', 'person'), your final answer MUST match that type. Re-check before finalising. "Boston" is wrong if the question asked for a country.

Excerpts:
{excerpts}

Question: {question}

Be concise (1 sentence ideally). Cite dia_id (e.g. D5:3) for the supporting excerpts.
Answer:"""


SYNTHESIZE_PROMPT_COUNTING = """You are answering a COUNTING / SUM question from a conversation transcript.

The user wants a NUMBER as the answer — count or total amount of something across all the picked excerpts. Do NOT enumerate items. Do NOT list dia_ids. Just produce the number (with a unit when relevant).

<reference_date>{reference_date}</reference_date>

YOUR ANSWER MUST BE A SINGLE NUMBER OR AMOUNT, optionally followed by a unit:
  - "How many doctors did I visit?" → "3" or "3 doctors"
  - "How much money have I spent on bikes?" → "$185"
  - "How many model kits?" → "5"
  - "How many days camping?" → "8 days"
  - "How many Korean restaurants?" → "4"

Do NOT respond with enumeration ("3: a primary care, an ENT specialist, a dermatologist"). The judge expects the count, not the items.

COUNTING PROTOCOL:
1. From the question, identify the COUNTABLE category (doctors, plants, hours, dollars, restaurants, etc.).
2. Scan EVERY excerpt for distinct mentions of that category. Read carefully — single sessions often mention multiple instances.
3. DEDUPE across excerpts: same item mentioned in two sessions counts ONCE. Different items in the same session count separately.
4. Sum the distinct items (or amounts) and output the integer / dollar total.
5. If the question asks "how much TOTAL X", sum dollar amounts across all mentions.

If genuinely no relevant info exists in the excerpts, respond exactly: "Not in the provided memories."

Excerpts:
{excerpts}

Question: {question}

Final answer (just a number with a unit, no enumeration):"""


SYNTHESIZE_PROMPT_LISTING = """You are answering a LISTING / AGGREGATION question by aggregating across multiple conversation excerpts.

<reference_date>{reference_date}</reference_date>

Use ONLY the conversation excerpts below.

LIST every distinct relevant item across the excerpts. Same fact mentioned in two sessions = ONE item (deduplicate). For each item:
- One short phrase or clause (no narrative).
- Cite the dia_id (e.g. D5:3) where it first appears.

If genuinely nothing in the excerpts answers, respond exactly: "Not in the provided memories."

Excerpts:
{excerpts}

Question: {question}

Format as a comma-separated list (e.g. "skiing (D1:3), painting (D4:2), running (D7:5)"). Don't ramble — every item should fit in one phrase. Answer:"""


EXPAND_PROMPT = """A first attempt to answer this question said "Not in the provided memories", but a broader sweep of the conversation may surface evidence the first picker missed.

Below is the conversation's table of contents. Pick a BROADER set of sections this time — 7-12 line_nums covering any session whose summary even tangentially relates to the question's subject, time period, or theme. Include neighbours of the originally-picked sections.

Originally picked (returned no answer): {prior_lines}

Pick line_nums ONLY from this allowlist: {valid_lines}

Tree:
{tree_json}

Question: {question}

Output ONLY a JSON object: {{"line_nums": [<int>, ...], "reason": "<one short sentence>"}}"""


async def _ask_picker(
    provider: OpenAIProvider, prompt: str, model: str,
    valid_lines: list[int],
) -> list[int]:
    """One picker call. Filters output to the allowlist, dedupes, caps
    at 12 (well above the picker's max-10 ask). When the picker
    returns an empty list (despite the prompt requiring ≥3 picks), or
    JSON parsing fails, falls back to a uniform sample across
    ``valid_lines`` so the synthesiser at least sees something — the
    synthesiser will then abstain correctly if the question truly has
    no answer in the conversation."""
    valid_set = set(valid_lines)
    pick_completion = await provider.complete(
        [Message(role="user", content=prompt)],
        model=model,
        max_tokens=300,
        temperature=0.0,
        response_format={"type": "json_object"},
    )
    out: list[int] = []
    try:
        pick = json.loads(pick_completion.text)
        raw = pick.get("line_nums") or []
        # Validate: only ints, only in allowlist, dedupe preserving order.
        seen: set[int] = set()
        for x in raw:
            try:
                n = int(x)
            except (TypeError, ValueError):
                continue
            if n in valid_set and n not in seen:
                seen.add(n)
                out.append(n)
            if len(out) >= 12:
                break
    except Exception:  # noqa: BLE001 — JSON parse fallback
        pass
    # Min-pick floor: smoke v5 (2026-05-09) showed the picker routinely
    # returning just [1] (title page) on multi-hop questions that asked
    # for 7-12 picks. That single pick slipped through the v4 safety
    # net (which only fired on empty/parse-fail), and the synthesiser
    # then hallucinated against the title-page excerpt.
    #
    # Padding strategy (revised v6→v7): use the FIRST N session anchors
    # (after stripping the title page line=1) rather than evenly-spaced.
    # Rationale: in LoCoMo, the relevant evidence overwhelmingly lives
    # in the early sessions where topics are introduced. Evenly-spaced
    # anchors over a 30-session conv hit lots of unrelated mid/late
    # sessions, which the synthesiser can't filter and which dilute
    # the right context. Early-bias matches the picker's natural
    # tendency to surface session 1 when uncertain.
    if not valid_lines:
        return out
    if len(out) < 4:
        # Drop the title-page line (line_num=1 is the document title,
        # not a session) when sampling. Keep it if it was a deliberate
        # pick, but don't pad with it.
        session_anchors = [ln for ln in valid_lines if ln > 1]
        seen2: set[int] = set(out)
        for ln in session_anchors:
            if ln not in seen2:
                out.append(ln)
                seen2.add(ln)
            if len(out) >= 5:
                break
    return out


# PR2 D.2: question-noun rescue stoplist. Words to exclude from the
# noun-grep fallback (function words + common verbs that would match
# every conversation). Different from _QUESTION_STOPWORDS below
# (which is for proper-noun extraction) — this list is bigger and
# lowercase-only.
_NOUN_RESCUE_STOPLIST = {
    # articles / determiners / quantifiers
    "the", "a", "an", "this", "that", "these", "those", "some", "any",
    "all", "many", "few", "much", "more", "most", "other", "another",
    "both", "each", "every", "either", "neither",
    # pronouns
    "i", "me", "my", "mine", "you", "your", "yours", "he", "him", "his",
    "she", "her", "hers", "it", "its", "we", "us", "our", "ours",
    "they", "them", "their", "theirs", "who", "whom", "whose", "what",
    "which", "where", "when", "why", "how",
    # common verbs that appear in questions
    "is", "are", "was", "were", "be", "been", "being", "am",
    "do", "does", "did", "doing", "done",
    "have", "has", "had", "having",
    "say", "said", "says", "saying", "tell", "told", "telling",
    "go", "went", "gone", "going", "get", "got", "getting",
    "take", "took", "taken", "taking", "make", "made", "making",
    "know", "knew", "known", "knowing", "think", "thought", "thinking",
    "want", "wanted", "wanting", "like", "liked", "liking",
    # prepositions / conjunctions
    "of", "in", "on", "at", "by", "for", "with", "without", "from",
    "to", "into", "onto", "from", "about", "against", "between",
    "through", "during", "before", "after", "above", "below", "since",
    "until", "as", "and", "or", "but", "if", "because", "so", "than",
    # generic question scaffolding
    "name", "names", "kind", "type", "thing", "things", "way", "ways",
    "time", "times", "place", "places",  # too generic for noun-grep
    "may", "might", "could", "would", "should", "must", "will", "can",
    # bench-specific scaffold
    "memory", "memories", "session", "sessions", "conversation",
    "answer", "question",
}


_QUESTION_STOPWORDS = {
    "What", "When", "Where", "Who", "Why", "How", "Which",
    "Did", "Does", "Do", "Is", "Was", "Were", "Are",
    "Has", "Have", "Had", "Would", "Could", "Should",
    "Will", "Can", "May", "Might", "Must", "Tell", "Name",
    "In", "On", "At", "By", "For", "Of", "About",
    "After", "Before", "During", "Since", "Until",
    "The", "A", "An", "This", "That", "These", "Those",
}


def _extract_question_nouns(question: str) -> list[str]:
    """PR2 D.2: pull lowercase content nouns from the question.

    Catches the common-noun anchors that ``_extract_question_entities``
    misses — words like 'pendant', 'obesity', 'dog treats', 'taekwondo',
    'France' that the open-domain failure analysis identified as the
    pivot for specific-fact questions.

    Heuristic: tokens of length ≥4 that aren't in the stoplist. We
    over-include rather than under-include — the noun-rescue grep
    filters by document content, so false-positive nouns just don't
    match anything.
    """
    # Lowercase + strip punctuation, split on whitespace
    cleaned = re.sub(r"[^\w\s]", " ", question.lower())
    tokens = cleaned.split()
    out: list[str] = []
    seen: set[str] = set()
    for t in tokens:
        if len(t) < 4:
            continue
        if t in _NOUN_RESCUE_STOPLIST:
            continue
        if t.isdigit():
            continue
        if t in seen:
            continue
        seen.add(t)
        out.append(t)
    return out


def _rescue_specific_fact_lines(
    question_nouns: list[str],
    md_text: str,
    *,
    valid_lines: list[int],
    max_rescues: int = 3,
) -> list[int]:
    """PR2 D.2: regex-grep the conversation markdown for question nouns.
    Return the line_nums of sessions whose body contains any noun.

    The picker / rerank pipeline routes on tree summaries; specific-fact
    questions ('country Jolene's mother bought pendant') hinge on body
    nouns that summaries elide. This function bypasses the summary
    layer and goes straight to the markdown.

    ``max_rescues`` caps the lift — we want to *augment* the picker's
    selection, not replace it. Returns a sorted list of line_nums to
    union into the picker's final picks.
    """
    if not question_nouns or not md_text or not valid_lines:
        return []
    # Build a regex matching any of the nouns as a word boundary.
    # Sort by length desc so longer nouns get checked first (more specific).
    sorted_nouns = sorted(set(question_nouns), key=len, reverse=True)
    pattern = re.compile(
        r"\b(" + "|".join(re.escape(n) for n in sorted_nouns) + r")\b",
        re.IGNORECASE,
    )

    lines = md_text.split("\n")
    valid_set = sorted(set(valid_lines))
    if not valid_set:
        return []

    # For each valid_line (a section anchor), check the section body
    # (from this line to the next valid_line) for a noun match. Return
    # at most ``max_rescues`` line_nums, ranked by hit-count desc so
    # the most-relevant section comes first.
    section_hits: list[tuple[int, int]] = []  # (line_num, hit_count)
    for i, ln in enumerate(valid_set):
        start = ln - 1  # 1-indexed line_num
        end = (valid_set[i + 1] - 1) if i + 1 < len(valid_set) else len(lines)
        if start < 0 or start >= len(lines):
            continue
        body = "\n".join(lines[start:end])
        hits = len(pattern.findall(body))
        if hits > 0:
            section_hits.append((ln, hits))

    section_hits.sort(key=lambda x: x[1], reverse=True)
    return [ln for ln, _ in section_hits[:max_rescues]]


def _extract_question_entities(question: str) -> list[str]:
    """Heuristic proper-noun extraction from a question (PR2 commit E).

    Pulls every Capitalised word, drops question-stopwords (``What``,
    ``When``, ``Did``, etc.). Replaced by an LLM-based extractor in
    PR2 commit D when the heuristic mis-routes too often.

    Each token is emitted separately — multi-word names like ``John
    Smith`` yield ``['John', 'Smith']`` so the entity strategy's
    case-insensitive ANY match in section_entities still hits. Dedupe
    is post-step.
    """
    tokens = re.findall(r"\b[A-Z][a-zA-Z]+\b", question)
    return list({t for t in tokens if t not in _QUESTION_STOPWORDS})


async def answer_question(
    provider: OpenAIProvider,
    conv_tree: dict,
    question: str,
    model: str,
    *,
    store=None,  # PageIndexStore | None — when set, use section recall path (PR2-E)
    bank_id: str | None = None,
    cross_encoder=None,  # CrossEncoderProtocol | None
    category: str | None = None,  # PR2-D.1: dataset-provided category label
) -> tuple[str, list[int]]:
    """Run the 2-step PageIndex agent loop for one question, with an
    iterative-expansion fallback when the first pick yields "Not in
    memories" on a non-adversarial-shaped question.

    PR2 commit E: when ``store`` + ``bank_id`` are provided AND the
    conv_tree carries a ``document_id``, the picker operates on a
    constrained skeleton produced by ``section_recall`` → cross-encoder
    rerank (top-15). Without those, falls back to the PR1 picker-on-
    full-skeleton path.

    Returns ``(answer, picked_line_nums)``.
    """
    # Step 1: pick.
    # ``md_to_tree`` returns ``{doc_name, line_count, structure: [...]}``.
    # The picker only cares about the navigable node list, so unwrap
    # to ``structure`` when present (older shapes returned a bare list).
    raw_tree = conv_tree["tree"]
    nodes = raw_tree.get("structure", raw_tree) if isinstance(raw_tree, dict) else raw_tree
    skeleton = _strip_node_text(nodes)
    valid_lines = _collect_valid_line_nums(skeleton)
    tree_json = json.dumps(skeleton, indent=2)

    # Mode dispatch — pick prompt and synth prompt match the question
    # shape. Listing/temporal questions need different selection biases
    # AND different synth modes (enumerate vs single-fact compose).
    # PR2-D.1: prefer the dataset's category label when provided —
    # the regex heuristic mis-routes LME's category names entirely.
    mode = _detect_question_mode(question, category=category)

    # PR2-E: section recall pre-filter. Run when the store backend has
    # populated entity + embedding indexes (PR2-A) so the orchestrator
    # has real signal to fuse. The picker still operates on a nested-
    # dict skeleton; we just narrow it to the top-15 reranked sections.
    document_id = conv_tree.get("document_id")
    # PR2 D.5.5: ``sections_by_key`` is hoisted to the outer scope so
    # the temporal-arithmetic short-circuit (later in this function)
    # can reach it. Built inside the section recall block; defaults to {}.
    sections_by_key: dict[tuple[str, int], PageIndexSection] = {}
    if store is not None and bank_id and document_id:
        from astrocyte.pipeline.question_annotator import annotate_question
        from astrocyte.pipeline.section_recall import section_recall  # local import to avoid heavy load on file backend
        from astrocyte.pipeline.section_rerank import (
            build_constrained_skeleton,
            rerank_fused_hits,
        )

        # PR2 D.5: single LLM call returns entities + date_range.
        # Replaces the regex ``_extract_question_entities`` (which only
        # caught Capitalised proper nouns) and the manual conv-range
        # date_range computation (which spanned the WHOLE conversation
        # and gave the temporal strategy nothing to filter on — that's
        # why LME temporal-reasoning stayed at 0% in PR2-D.1-4).
        annotation = await annotate_question(
            provider, question,
            reference_date=conv_tree.get("reference_date"),
            model=model,
        )
        question_entities = annotation.entities
        date_range = annotation.date_range

        # PR2 D.5-fallback: when the question is temporally-routed but
        # the LLM didn't extract a specific date anchor ("When did X
        # happen?" — no date in the question text), fall back to the
        # conversation's full date range so the temporal strategy at
        # least contributes session-date ordering. Without this fallback
        # LoCoMo temporal regresses 55→45 because temporal strategy
        # silently doesn't fire on date-less temporal questions.
        if (
            date_range is None
            and mode in {"temporal", "temporal-reasoning"}
            and conv_tree.get("session_dates")
        ):
            from datetime import timedelta
            parsed = [
                _parse_session_date(d) for _, d in conv_tree["session_dates"]
            ]
            parsed = [p for p in parsed if p is not None]
            if parsed:
                date_range = (min(parsed), max(parsed) + timedelta(days=1))

        try:
            recall_result = await section_recall(
                store=store, bank_id=bank_id, question=question, mode=mode,
                embedding_provider=provider,
                question_entities=question_entities or None,
                date_range=date_range,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"  [pageindex] section_recall failed for q={question[:40]!r}: {type(exc).__name__}: {exc}")
            recall_result = None

        if recall_result and recall_result.fused:
            # Build sections_by_key from the existing skeleton — no
            # extra DB call. (Hoisted to outer scope above; just
            # populate here.)

            def _walk_collect(items):
                if not isinstance(items, list):
                    return
                for n in items:
                    if not isinstance(n, dict):
                        continue
                    ln = n.get("line_num")
                    if isinstance(ln, int):
                        # PR2 D.5.5c: populate session_date from the
                        # in-memory tree's ``date`` string (set by
                        # ``_enrich_nodes_with_dates`` at build time).
                        # Without this, every section had session_date=None
                        # and D.5.5 had to lazy-load from the store.
                        sections_by_key[(document_id, ln)] = PageIndexSection(
                            document_id=document_id,
                            line_num=ln,
                            node_id=n.get("node_id", ""),
                            title=n.get("title", "") or "",
                            summary=n.get("summary"),
                            session_date=_parse_session_date(n.get("date")),
                            depth=0,
                        )
                    _walk_collect(n.get("nodes"))

            _walk_collect(skeleton)
            try:
                # PR2-C tuning: cut at top-25 instead of top-15 — first
                # smoke (30% overall vs PR1's 62%) showed multi-hop
                # questions losing the second-source session when the
                # cross-encoder ranked it below 15. Multi-hop needs
                # ≥2 sources; the rerank is too confident on single-
                # best matches. Top-25 drops only the bottom 5 of a
                # ~30-section conv — keeps almost everything visible
                # while still removing clearly-irrelevant nodes.
                #
                # We ALSO keep the original ``valid_lines`` (full set)
                # as the picker's allowlist — the constrained skeleton
                # is a strong hint, but the picker can still pick any
                # line_num if it disagrees with the rerank. This is
                # the v6 lesson re-applied: don't lock the picker out
                # of evidence the orchestrator missed.
                reranked = rerank_fused_hits(
                    recall_result.fused, sections_by_key, question,
                    model=cross_encoder, rerank_top_k=30, output_top_k=25,
                )
                if reranked:
                    keep_keys = {(h.document_id, h.line_num) for h in reranked}
                    constrained = build_constrained_skeleton(
                        skeleton, keep_keys, document_id,
                    )
                    if constrained:
                        # NOTE: ``skeleton`` and ``valid_lines`` deliberately
                        # NOT narrowed — the picker can still address sections
                        # outside the constrained tree if it remembers the
                        # topic. Only the JSON tree shown to the LLM is
                        # rebuilt to highlight the reranked subset.
                        tree_json = json.dumps(constrained, indent=2)
            except Exception as exc:  # noqa: BLE001
                print(f"  [pageindex] rerank failed: {type(exc).__name__}: {exc}")
    reference_date = conv_tree.get("reference_date") or "unknown"
    session_dates = conv_tree.get("session_dates") or []
    session_date_index = "\n".join(
        f"  line {ln}: {d}" for ln, d in session_dates
    ) or "  (none — header dates not parseable)"

    # PR2.5: counting/sum dispatch — REVERTED.
    # Tested: counting synth correctly produces a number ("2 items",
    # "$65") but PICKER still undercounts (fetches 5-6 sections when
    # answer requires 8-10 mentions). Multi-session unchanged at 1/9;
    # other categories regressed (single-session-user 78→67, single-
    # session-preference 38→25, LME overall 46→42).
    # Counting needs DETERMINISTIC entity-based aggregation over all
    # mentioning sections (not LLM), which is a separate piece of
    # work. Accepting LME multi-session at 11% for PR2 close.
    is_counting = False

    if mode == "temporal":
        pick_msg = PICK_PROMPT_TEMPORAL.format(
            tree_json=tree_json,
            question=question,
            valid_lines=valid_lines,
            session_date_index=session_date_index,
            reference_date=reference_date,
        )
    elif mode == "listing" or is_counting:
        pick_msg = PICK_PROMPT_LISTING.format(
            tree_json=tree_json,
            question=question,
            valid_lines=valid_lines,
        )
    else:
        pick_msg = PICK_PROMPT_DEFAULT.format(
            tree_json=tree_json,
            question=question,
            valid_lines=valid_lines,
        )
    line_nums = await _ask_picker(provider, pick_msg, model, valid_lines)

    # PR2 D.2: question-noun rescue. Specific-fact questions ('country
    # Jolene's mother bought pendant') hinge on body nouns that
    # summaries elide — the picker can't see them. Grep the markdown
    # for question nouns and union the matching sessions into the
    # picker's selection. We DON'T replace the picker — just augment.
    # No-op when the question has no extractable nouns or no body
    # match (so listing/inference questions aren't perturbed).
    #
    # Disabled for:
    # - adversarial: LoCoMo adversarial works best when synth abstains;
    #   injecting noun-rescued sections gives it false context.
    # - temporal modes: subject names (Caroline, John) appear in nearly
    #   every session; noun-rescue floods the synth with off-date
    #   sessions and dilutes the temporal signal. The temporal strategy
    #   already pre-filters by date — let it do its job. PR2-D.1-4
    #   gate showed -10pp on LoCoMo temporal when rescue was active
    #   for these modes.
    if category != "adversarial" and mode not in {"temporal", "temporal-reasoning"}:
        question_nouns = _extract_question_nouns(question)
        rescued = _rescue_specific_fact_lines(
            question_nouns, conv_tree["md_text"],
            valid_lines=valid_lines, max_rescues=3,
        )
        if rescued:
            # Union with picker output, preserving picker's order first
            # (the picker's reasoning is primary; rescue is augmentation).
            seen_ln = set(line_nums)
            for ln in rescued:
                if ln not in seen_ln:
                    line_nums.append(ln)
                    seen_ln.add(ln)

    # Step 2: fetch sections.
    if line_nums:
        excerpts = "\n\n---\n\n".join(
            _slice_section_around_line(conv_tree["md_text"], ln)
            for ln in line_nums
        ).strip()
    else:
        excerpts = ""

    if not excerpts:
        # The picker couldn't (or wouldn't) route. Tell the synthesizer
        # nothing's in scope — let it answer "Not in the provided
        # memories." which is the right outcome on adversarial Qs.
        excerpts = "(no relevant section found)"

    # PR2 D.5.5c: structured-dates synth context — REVERTED.
    # Tested in two gates:
    #   v1 (both temporal modes): LoCoMo temporal 55→27% (synth used
    #     session_date as event_date), LME temporal-reasoning still 0%.
    #   v2 (LME-only gate): LME temporal-reasoning still 0% AND
    #     other LME categories regressed (multi-session 11→0,
    #     single-session-* down 10pp each).
    # Both runs proved: the structured-dates block either substitutes
    # session_date for the correct in-dialogue event date (LoCoMo) or
    # doesn't help arithmetic the synth can't do anyway (LME).
    #
    # The session_date population in _walk_collect (above) STAYS as a
    # bug fix — it lets D.5.5's arithmetic short-circuit work without
    # lazy-loading from the store.

    # Listing questions get the union/dedupe synth; everything else
    # uses the default synth (which now carries the reference_date
    # block for temporal-relative phrases).
    #
    # PR2 D.3: inference questions get a permissive synth that's
    # instructed to read between the lines. Routes when:
    #   - Category is open-domain or single-session-preference (dataset signal), OR
    #   - The question text matches an inference pattern (regex fallback).
    # PR2 D.4: answer-type hint goes to the inference synth so it
    # verifies its final answer matches the asked-for type.
    is_inference = (
        category in {"open-domain", "single-session-preference"}
        or _is_inference_question(question)
    )

    # PR2 D.5.5: programmatic date-arithmetic short-circuit. LME
    # temporal-reasoning is 0% across PR2/D.1-4/D.4-fix/D.5 because
    # questions like "how many days between A and B?" require date
    # arithmetic gpt-4o-mini can't reliably do. We have all three
    # dates structured in section.session_date — compute in Python.
    #
    # Only fires when:
    #   - The store-backed section recall path was taken (sections_by_key was built).
    #   - mode is temporal/temporal-reasoning (gates against false-positive
    #     regex matches in non-temporal questions).
    #   - The arithmetic module recognizes the question shape AND finds
    #     the events in the document. Otherwise falls through to synth.
    arithmetic_answer: str | None = None
    if (
        store is not None and bank_id and document_id
        and mode in {"temporal", "temporal-reasoning"}
    ):
        from astrocyte.pipeline.temporal_arithmetic import (
            compute_temporal_arithmetic_answer,
        )
        # ``sections_by_key`` was built earlier in the section recall block;
        # reach for it from the outer scope. ``reference_date_dt`` is
        # parsed from conv_tree.reference_date (a string).
        ref_dt = _parse_session_date(reference_date) if reference_date != "unknown" else None
        try:
            arithmetic_answer = await compute_temporal_arithmetic_answer(
                store=store,
                bank_id=bank_id,
                document_id=document_id,
                question=question,
                sections_by_key=sections_by_key,
                reference_date_dt=ref_dt,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"  [pageindex] temporal_arithmetic failed: {type(exc).__name__}: {exc}")
            arithmetic_answer = None

    if arithmetic_answer is not None:
        # Skip the synth — return the computed answer directly.
        answer = arithmetic_answer
        return answer, line_nums

    if is_counting:
        # PR2.5: counting questions use a dedicated synth that
        # outputs a NUMBER (not an enumeration). Picker stayed as
        # listing-shape so synth has many sections to count over.
        syn_msg = SYNTHESIZE_PROMPT_COUNTING.format(
            excerpts=excerpts, question=question, reference_date=reference_date,
        )
        syn_max_tokens = 80  # answers are short ("3", "$185") — cap tight to suppress enumeration
    elif mode == "listing":
        syn_msg = SYNTHESIZE_PROMPT_LISTING.format(
            excerpts=excerpts, question=question, reference_date=reference_date,
        )
        syn_max_tokens = 400  # listing answers are longer than 1-fact answers
    elif is_inference and category != "adversarial":
        syn_msg = SYNTHESIZE_PROMPT_INFERENCE.format(
            excerpts=excerpts, question=question, reference_date=reference_date,
            answer_type_hint=_detect_answer_type_hint(question) or "(no hint)",
        )
        syn_max_tokens = 200
    else:
        syn_msg = SYNTHESIZE_PROMPT_DEFAULT.format(
            excerpts=excerpts, question=question, reference_date=reference_date,
        )
        syn_max_tokens = 250

    syn_completion = await provider.complete(
        [Message(role="user", content=syn_msg)],
        model=model,
        max_tokens=syn_max_tokens,
        temperature=0.0,
    )
    answer = syn_completion.text.strip()

    # Iterative expansion: if the first attempt returned the
    # abstention sentinel AND the picker DID select sections (i.e.
    # the picker thought there was something there but the picked
    # sections didn't pan out), retry with a broader pick. This
    # specifically targets multi-hop/temporal questions where the
    # first picker undershoots — the smoke run on 2026-05-09
    # observed the picker routinely selecting 1-2 sections and
    # missing 3-4 other sessions that contained chained evidence.
    #
    # We DON'T retry when the picker returned an empty list — that's
    # the adversarial-correct outcome (no relevant section exists)
    # and re-running would just risk fabricating a wrong answer.
    abstained = "not in the provided memories" in answer.lower()
    if abstained and line_nums and len(line_nums) < len(valid_lines):
        expand_msg = EXPAND_PROMPT.format(
            tree_json=tree_json,
            question=question,
            valid_lines=valid_lines,
            prior_lines=line_nums,
        )
        wider_lines = await _ask_picker(provider, expand_msg, model, valid_lines)
        # Merge with prior picks — neighbours might still be useful.
        merged = list(dict.fromkeys([*line_nums, *wider_lines]))[:12]
        if merged != line_nums:  # actually expanded
            wider_excerpts = "\n\n---\n\n".join(
                _slice_section_around_line(conv_tree["md_text"], ln)
                for ln in merged
            ).strip() or "(no relevant section found)"
            # Use the same mode-appropriate synth on expansion. Listing
            # mode benefits most from the wider sweep (more items to
            # enumerate); temporal/default benefit from the broader
            # multi-hop chain assembly.
            if mode == "listing":
                syn_msg2 = SYNTHESIZE_PROMPT_LISTING.format(
                    excerpts=wider_excerpts, question=question,
                    reference_date=reference_date,
                )
                syn2_max = 400
            else:
                syn_msg2 = SYNTHESIZE_PROMPT_DEFAULT.format(
                    excerpts=wider_excerpts, question=question,
                    reference_date=reference_date,
                )
                syn2_max = 300
            syn_completion2 = await provider.complete(
                [Message(role="user", content=syn_msg2)],
                model=model,
                max_tokens=syn2_max,
                temperature=0.0,
            )
            answer = syn_completion2.text.strip()
            line_nums = merged
    return answer, line_nums


# ───────────────────────────────────────────────────────────────────────────
# Scoring + driver
# ───────────────────────────────────────────────────────────────────────────

def stratified_questions(
    locomo_data: list[dict], max_per_conversation: int,
) -> list[dict]:
    """Take up to N questions per conversation, balanced across
    categories. Mirrors ``bench-locomo-fair`` semantics so the result
    is comparable to the in-tree bench."""
    out: list[dict] = []
    for conv in locomo_data:
        sample_id = conv["sample_id"]
        qs = conv.get("qa") or []
        # Group by category and round-robin-pull until we hit the cap
        # or run out — matches the harness's stratified sampler.
        by_cat: dict[int, list[dict]] = {}
        for q in qs:
            by_cat.setdefault(q.get("category", 0), []).append(q)
        picks: list[dict] = []
        cat_iters = {c: iter(qlist) for c, qlist in by_cat.items()}
        while len(picks) < max_per_conversation and cat_iters:
            done: list[int] = []
            for c, it in list(cat_iters.items()):
                try:
                    picks.append(dict(next(it), conversation_id=sample_id))
                except StopIteration:
                    done.append(c)
                if len(picks) >= max_per_conversation:
                    break
            for c in done:
                cat_iters.pop(c, None)
        out.extend(picks)
    return out


async def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--locomo-path",
        default="datasets/locomo/data/locomo10.json",
        help="Path to LoCoMo10 JSON dataset.",
    )
    parser.add_argument(
        "--workspace",
        default="benchmark-results/pageindex/locomo",
        help="Where to cache markdown + tree JSON between runs.",
    )
    parser.add_argument(
        "--model",
        default="gpt-4o-mini",
        help="LLM model for tree-build, picker, synthesizer, and judge.",
    )
    parser.add_argument(
        "--max-questions-per-conversation",
        type=int,
        default=20,
        help="Stratified per-conversation cap; 20×10=200 total questions.",
    )
    parser.add_argument(
        "--no-judge",
        action="store_true",
        help="Skip LLM judging — useful for a smoke run that just dumps responses.",
    )
    # PR1 commit D — backend dispatch via PageIndexStore SPI.
    #
    # ``file`` (default): Phase A POC behaviour — tree.json on disk under
    # ``--workspace``. No DB. The smoke loop you've been iterating on.
    #
    # ``memory``: ``InMemoryPageIndexStore``; trees live for the life of
    # the process. Useful for catching SPI-conformance regressions
    # without standing up a DB.
    #
    # ``postgres``: ``PostgresPageIndexStore``; persisted across runs in
    # a real DB. Requires DATABASE_URL or ASTROCYTE_PG_DSN. The
    # production path section recall will use; bench gate runs on this.
    parser.add_argument(
        "--backend",
        choices=("file", "memory", "postgres"),
        default="file",
        help="Where to cache PageIndex trees (PR1 commit D, M9 / ADR-006).",
    )
    parser.add_argument(
        "--bank-id",
        default="bench-pageindex-locomo",
        help="Bank id used when --backend in {memory,postgres}; ignored otherwise.",
    )
    args = parser.parse_args()

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise SystemExit("OPENAI_API_KEY not set; run via 'doppler run --'.")

    workspace = Path(args.workspace)
    workspace.mkdir(parents=True, exist_ok=True)

    # ── Backend dispatch ──
    store = None
    if args.backend == "memory":
        store = InMemoryPageIndexStore()
        print(f"  [pageindex] Backend: in-memory (bank_id={args.bank_id!r})")
    elif args.backend == "postgres":
        # Lazy import so the file/memory paths don't pay for the
        # adapter dep chain (psycopg pool, etc).
        from astrocyte_postgres import PostgresPageIndexStore  # noqa: PLC0415
        store = PostgresPageIndexStore(bootstrap_schema=True)
        print(f"  [pageindex] Backend: postgres (bank_id={args.bank_id!r})")
    else:
        print(f"  [pageindex] Backend: file ({workspace})")

    print(f"  [pageindex] Loading LoCoMo from {args.locomo_path}...")
    locomo_data = json.loads(Path(args.locomo_path).read_text())
    print(f"  [pageindex] Loaded {len(locomo_data)} conversations")

    # Provider is constructed up-front so the same instance powers
    # tree-build entity+embedding pass (PR2 commit A), per-question
    # picker / synth, and the judge. Same model, same auth path, single
    # connection pool.
    provider = OpenAIProvider(api_key=api_key, model=args.model)

    # ── Step 1: build (or load cached) per-conversation trees.
    #
    # Done sequentially so the printed log is readable. md_to_tree
    # already parallelizes summary generation internally, so wall-time
    # gain from gathering at this level is small. The entity+embedding
    # pass (PR2 commit A) only fires for store-backed runs on a fresh
    # cache miss.
    trees_by_sample: dict[str, dict] = {}
    t_build = time.monotonic()
    for conv in locomo_data:
        sample_id = conv["sample_id"]
        trees_by_sample[sample_id] = await build_or_load_tree(
            conv, sample_id, workspace, args.model,
            store=store,
            bank_id=args.bank_id,
            provider=provider if store is not None else None,
            entity_model=args.model,
            embedding_model=None,  # use provider's default embedding model
        )
    build_elapsed = time.monotonic() - t_build
    print(f"  [pageindex] All trees ready in {build_elapsed:.1f}s")

    # ── Step 2: stratified question slice.
    questions = stratified_questions(locomo_data, args.max_questions_per_conversation)
    print(f"  [pageindex] Scoring {len(questions)} questions ({args.max_questions_per_conversation} per conv)")

    # ── Step 3: judge setup (re-uses the provider above).
    judge = LoCoMoLLMJudge(provider, model=args.model) if not args.no_judge else None

    # ── Step 4: per-question agent + judge.
    results: list[dict] = []
    correct = 0
    by_category_correct: dict[str, int] = {}
    by_category_total: dict[str, int] = {}
    t_score = time.monotonic()
    for i, q in enumerate(questions):
        sample_id = q["conversation_id"]
        conv_tree = trees_by_sample[sample_id]
        # PR2-D.1: pass the dataset's category label so mode dispatch
        # uses it directly instead of the regex heuristic.
        cat_int = q.get("category")
        cat_label = _CATEGORY_MAP.get(cat_int) if cat_int is not None else None
        try:
            answer, line_nums = await answer_question(
                provider, conv_tree, q["question"], args.model,
                store=store,
                bank_id=args.bank_id if store is not None else None,
                cross_encoder=None,  # PR2-C: default Hindsight model lazy-loaded inside reranker
                category=cat_label,
            )
        except Exception as exc:  # noqa: BLE001 — single-Q failure mustn't tank the run
            print(f"  [pageindex] Q{i} failed: {exc}")
            answer, line_nums = "(error)", []

        # LoCoMo's category-5 (adversarial) questions have no
        # ``answer`` field — the dataset uses ``adversarial_answer`` to
        # record the plausible-but-wrong answer the model should NOT
        # regurgitate. The canonical judge already ignores ``answer``
        # for adversarial scoring (it just checks for an abstention
        # signal in the response), but we still pass an empty string
        # to keep the .format() call shape-stable. We persist
        # ``adversarial_answer`` separately for failure analysis.
        is_adversarial = q.get("category") == 5
        expected_for_judge = "" if is_adversarial else str(q.get("answer", ""))
        expected_for_log = q.get("answer") if not is_adversarial else q.get("adversarial_answer")

        is_correct: float = 0.0
        if judge is not None and answer != "(error)":
            try:
                is_correct = await judge.score(
                    question=q["question"],
                    answer=expected_for_judge,
                    category=_CATEGORY_MAP.get(q["category"], str(q["category"])),
                    response=answer,
                )
            except Exception as exc:  # noqa: BLE001 — judge failure shouldn't kill the run
                print(f"  [pageindex] Q{i} judge failed: {exc}")
                is_correct = 0.0

        cat_name = _CATEGORY_MAP.get(q["category"], str(q["category"]))
        by_category_total[cat_name] = by_category_total.get(cat_name, 0) + 1
        if is_correct >= 1.0:
            correct += 1
            by_category_correct[cat_name] = by_category_correct.get(cat_name, 0) + 1

        results.append({
            "conversation_id": sample_id,
            "category": cat_name,
            "question": q["question"],
            "expected": expected_for_log,
            "is_adversarial": is_adversarial,
            "response": answer,
            "score": is_correct,
            "picked_lines": line_nums,
        })

        if (i + 1) % 10 == 0:
            elapsed = time.monotonic() - t_score
            running = correct / (i + 1)
            print(
                f"  [pageindex] {i + 1}/{len(questions)} — running accuracy {running:.3f} "
                f"({correct}/{i + 1}) — {elapsed:.0f}s elapsed",
            )

    # ── Step 5: report.
    overall = correct / max(len(questions), 1)
    print()
    print(f"  [pageindex] OVERALL ACCURACY: {overall:.4f} ({correct}/{len(questions)})")
    print()
    print("  [pageindex] per-category:")
    for cat in sorted(by_category_total):
        n = by_category_total[cat]
        c = by_category_correct.get(cat, 0)
        print(f"    {cat:<12} {c}/{n}  ({c / max(n, 1):.4f})")

    # Persist a compact result file so future iteration can compare
    # against this run without re-running the whole bench.
    out_path = workspace / f"results-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.json"
    out_path.write_text(json.dumps({
        "overall_accuracy": overall,
        "evaluated_questions": len(questions),
        "correct": correct,
        "category_accuracy": {
            cat: by_category_correct.get(cat, 0) / max(by_category_total[cat], 1)
            for cat in by_category_total
        },
        "model": args.model,
        "max_questions_per_conversation": args.max_questions_per_conversation,
        "results": results,
    }, indent=2, default=str))
    print(f"  [pageindex] Results written to {out_path}")


if __name__ == "__main__":
    asyncio.run(main())
